use super::{Building, SettlementConfig, SettlementTier};
use crate::game::generation::structure_library::{Structure, StructureLibrary, StructureUsage};
use rand::Rng;

/// Convert PascalCase faction ID (from factions.json) to snake_case (used in structures.json)
fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}

/// Clockwise rotation (0/90/180/270) that makes `entrance_side` face `target_dir`.
fn rotation_to_face(entrance_side: &str, target_dir: &str) -> u16 {
    const DIRS: [&str; 4] = ["north", "east", "south", "west"];
    let idx = |d: &str| DIRS.iter().position(|&x| x == d).unwrap_or(2);
    let steps = (idx(target_dir) + 4 - idx(entrance_side)) % 4;
    steps as u16 * 90
}

/// Cardinal direction from `from` toward `to` (screen coords: y increases downward).
fn toward(from: (f32, f32), to: (f32, f32)) -> &'static str {
    let (dx, dy) = (to.0 - from.0, to.1 - from.1);
    if dx.abs() >= dy.abs() {
        if dx >= 0.0 { "east" } else { "west" }
    } else {
        if dy >= 0.0 { "south" } else { "north" }
    }
}

/// Place buildings at positions generated by layout::generate_layout()
pub fn place_buildings<R: Rng>(
    config: &SettlementConfig,
    width: usize,
    height: usize,
    rng: &mut R,
) -> Vec<Building> {
    let library = match StructureLibrary::load() {
        Ok(lib) => lib,
        Err(_) => return Vec::new(),
    };

    let dominant_faction = super::faction_theme::get_dominant_faction(config);

    let candidates: Vec<_> = match &dominant_faction {
        Some(faction) => {
            let snake = to_snake_case(faction);
            let faction_buildings = library.by_faction(&snake);
            if faction_buildings.is_empty() {
                library.by_usage(StructureUsage::Connectable)
            } else {
                faction_buildings
            }
        }
        None => library.by_usage(StructureUsage::Connectable),
    };

    if candidates.is_empty() {
        return Vec::new();
    }

    let max_buildings = match config.tier {
        SettlementTier::Village => 6,
        SettlementTier::Town => 12,
        SettlementTier::City => 20,
    };

    let positions = super::layout::generate_layout(config, width, height, rng);
    let centroid = (width as f32 / 2.0, height as f32 / 2.0);

    // Track placed footprints as (x, y, w, h) for overlap rejection
    let mut placed: Vec<(i32, i32, i32, i32)> = Vec::new();
    const PAD: i32 = 2; // minimum gap between buildings

    let mut buildings = Vec::new();
    for (x, y) in positions.into_iter().take(max_buildings * 2) {
        if buildings.len() >= max_buildings {
            break;
        }

        let total_weight: f32 = candidates.iter().map(|s| s.metadata.weight).sum();
        let mut roll = rng.gen_range(0.0f32..total_weight.max(1.0));
        let structure: &Structure = candidates
            .iter()
            .find(|s| {
                if roll < s.metadata.weight {
                    true
                } else {
                    roll -= s.metadata.weight;
                    false
                }
            })
            .unwrap_or(&candidates[0]);

        let entrance = structure
            .metadata
            .entrance_side
            .as_deref()
            .unwrap_or("south");
        let rotation = if entrance == "any" {
            0
        } else {
            let bx = x as f32 + structure.width as f32 / 2.0;
            let by = y as f32 + structure.height as f32 / 2.0;
            let target = toward((bx, by), centroid);
            rotation_to_face(entrance, target)
        };

        let (ew, eh) =
            super::effective_dims(structure.width as i32, structure.height as i32, rotation);

        // Check overlap with already-placed buildings
        let overlaps = placed.iter().any(|&(px, py, pw, ph)| {
            x < px + pw + PAD && x + ew + PAD > px && y < py + ph + PAD && y + eh + PAD > py
        });
        if overlaps {
            continue;
        }

        placed.push((x, y, ew, eh));
        buildings.push(Building {
            prefab_name: structure.id.clone(),
            x,
            y,
            faction: dominant_faction.clone(),
            rotation,
        });
    }
    buildings
}
