use super::{Building, SettlementConfig, SettlementTier};
use crate::game::generation::structure_library::{StructureLibrary, StructureUsage};
use rand::Rng;

/// Convert PascalCase faction ID (from factions.json) to snake_case (used in structures.json)
fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}

/// Place buildings at positions generated by layout::generate_layout()
pub fn place_buildings<R: Rng>(
    config: &SettlementConfig,
    width: usize,
    height: usize,
    rng: &mut R,
) -> Vec<Building> {
    let library = match StructureLibrary::load() {
        Ok(lib) => lib,
        Err(_) => return Vec::new(),
    };

    let dominant_faction = super::faction_theme::get_dominant_faction(config);

    let candidates: Vec<_> = match &dominant_faction {
        Some(faction) => {
            // structures.json uses snake_case faction IDs; factions.json uses PascalCase
            let snake = to_snake_case(faction);
            let faction_buildings = library.by_faction(&snake);
            if faction_buildings.is_empty() {
                library.by_usage(StructureUsage::Connectable)
            } else {
                faction_buildings
            }
        }
        None => library.by_usage(StructureUsage::Connectable),
    };

    if candidates.is_empty() {
        return Vec::new();
    }

    let max_buildings = match config.tier {
        SettlementTier::Village => 6,
        SettlementTier::Town => 12,
        SettlementTier::City => 20,
    };

    let positions = super::layout::generate_layout(config, width, height, rng);

    positions
        .into_iter()
        .take(max_buildings)
        .map(|(x, y)| {
            let total_weight: f32 = candidates.iter().map(|s| s.metadata.weight).sum();
            let mut roll = rng.gen_range(0.0f32..total_weight.max(1.0));
            let structure = candidates
                .iter()
                .find(|s| {
                    if roll < s.metadata.weight {
                        true
                    } else {
                        roll -= s.metadata.weight;
                        false
                    }
                })
                .unwrap_or(&candidates[0]);

            Building {
                prefab_name: structure.id.clone(),
                x,
                y,
                faction: dominant_faction.clone(),
            }
        })
        .collect()
}
